on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3 
    - name: Set up Emacs
      uses: purcell/setup-emacs@v3.0
      with:
        version: 28.1

    - name: Emacs init
      run: bin/setup

    - name: examples
      run: bin/test
